# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e70d70bab5d6a39b1c214472ede8d5ea3406281675b6f197f854ce910de58ceb1a658b498994b4430d54944e91b48523a889470ed04059b49d78d320fb77a1f8

test:
  secret_key_base: c9a664974266b30e4f7db5babb15a807d25dac0d301ff7bb39d819b019a27c0793c248c7149a60e26fc85a56d6e77ebc8edf45092f77ec630dc87b7a5aa037cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
